name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    stratergy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v3
      - name: Restore the dependencies
        run: npm ci
      - name: Build
        run: npm run all


